[package]
name = "truthfy"
version = "0.7.0"
entrypoint = "src/main.typ"
authors = ["Quemin Thomas <@Thumuss>"]
license = "MIT"
description = "Generate truth tables effortlessly — manual or automatic."
repository = "https://github.com/Thumuss/truthfy"
keywords = [
    "truth",
    "table",
]
exclude = ["examples", ".gitignore"]
